# Generate self-signed OpenSSL certificate 
---
- name: Create directory for local self-signed TLS certs
  ansible.builtin.file:
    path: /etc/pki/tls/{{ certificate.host }}
    state: directory
    mode: '0750'

- name: Generate an OpenSSL private key
  community.crypto.openssl_privatekey:
    path: /etc/pki/tls/{{ certificate.host }}/private.pem
    size: 2048
    type: ECC
    curve: secp384r1

- name: Generate an OpenSSL CSR
  community.crypto.openssl_csr:
    path: /etc/pki/tls/{{ certificate.host }}/{{ certificate.host }}.csr
    privatekey_path: /etc/pki/tls/{{ certificate.host }}/private.pem
    common_name: "{{ certificate.domain }}"
    organization_name: OPEN MIND
    country_name: NG
    create_subject_key_identifier: yes
    #ocsp_must_staple: yes

- name: Generate a self-signed OpenSSL certificate
  community.crypto.x509_certificate:
    path: /etc/pki/tls/{{ certificate.host }}/chain.crt
    privatekey_path: /etc/pki/tls/{{ certificate.host }}/private.pem
    csr_path: /etc/pki/tls/{{ certificate.host }}/{{ certificate.host }}.csr
    provider: selfsigned
    selfsigned_not_after: "+365d"
    
- name: Generate Diffie-Hellman parameters with 2048 bits
  community.crypto.openssl_dhparam:
    path: /etc/pki/tls/{{ certificate.host }}/dhparams.pem
    size: 2048


- name: Add self-signed certificate to trusted CA bundle
#  ansible.builtin.command: import keytool


#- name: Generate SSH key pair
#  ansible.builtin.command: ssh-keygen -P {{ssh.pass}} -t ecdsa -b 384 -f '{{ ssh.path }}/id_ecdsa'
#  become: yes
#  become_user: vagrant

- name: Generate an OpenSSH key
  community.crypto.openssh_keypair:
    path: '{{ ssh.path }}/id_ecdsa'
    type: ecdsa
    size: 384
  become: yes
  become_user: '{{ ssh.owner }}'

- name: Ensure ssh-agent is running
  ansible.builtin.shell: eval $(ssh-agent)

- name: Register key with ssh-agent
  ansible.builtin.command: ssh-add {{ ssh.path }}/id_ecdsa